### ISSUE TITLE
Option to turn off on android

### ISSUE THREAD

**Issue by andrey-skl** [Andr3wHur5t/react-native-keyboard-spacer#17]
On Android, view height is decreased by android itself when open keyboard. So here KeyboardSpacer not needed.
<img width="539" alt="screen shot 2016-04-11 at 14 19 53" src="https://cloud.githubusercontent.com/assets/4318513/14425519/7f7eed28-fff0-11e5-92b0-cbed92af4e07.png">

**Comment by sodik82** [comment]
I believe it is not a problem to wrap `KeyboardSpacer` into your own component and don't render it for android. It seems better option that if you would have to use `disableAndroid` property for all instances in your application.

**Comment by andrey-skl** [comment]
@sodik82 makes sense. Lets go this way, thanks.
