### ISSUE TITLE
[Warning]`keyboardWillShow` event should be registered via the Keyboard module

### ISSUE THREAD

**Issue by zeo112140** [Andr3wHur5t/react-native-keyboard-spacer#23]
The Latest version of React-native， import the module ‘react-native-keyboard-spacer’ , found a warning `keyboardWillShow` event should be registered via the Keyboard module，`keyboardWillHide` event should be registered via the Keyboard module,How to deal with the warning？

**Comment by Andr3wHur5t** [comment]
Where are you seeing this warning and what version of react native are you using?

**Comment by akovantsev** [comment]
@Andr3wHur5t those warnings are being shown on `DeviceEventEmitter.addListener` call.

```
      "react": "^15.1.0",
      "react-native": "^0.27.0-rc2"
```

use Keyboard instead (clojurescript):
https://github.com/facebook/react-native/blob/master/Libraries/Components/Keyboard/Keyboard.js

```
(def Keyboard (js/require "Keyboard"))
(.addListener Keyboard "keyboardWillShow" callback)
```

**Comment by zeo112140** [comment]
thank you, i got it.

------------------ 原始邮件 ------------------
发件人: "misha akovantsev";notifications@github.com;
发送时间: 2016年6月3日(星期五) 晚上10:25
收件人: "Andr3wHur5t/react-native-keyboard-spacer"react-native-keyboard-spacer@noreply.github.com; 
抄送: "cc"7453027@qq.com; "Author"author@noreply.github.com; 
主题: Re: [Andr3wHur5t/react-native-keyboard-spacer][Warning]`keyboardWillShow` event should be registered via the Keyboard module(#23)

@Andr3wHur5t those warnings are being shown on DeviceEventEmitter.addListener call.
       "react": "^15.1.0",       "react-native": "^0.27.0-rc2"

**Comment by Andr3wHur5t** [comment]
I'm working on a backwards compatible fix, time permitting I'll get a PR out soon.

**Comment by deju** [comment]
`import {Keyboard} from 'react-native';`

`Keyboard.addListener('keyboardWillShow', (e) => this._keyboardWillShow(e));`

**Comment by joonhocho** [comment]
How to remove?

**Comment by JanPeter** [comment]
@joonhocho seems for me that this code is working:

```
  componentWillMount() {
    this.keyboardWillShowSub = Keyboard.addListener('keyboardWillShow', this.keyboardWillShow.bind(this));
    this.keyboardWillHideSub = Keyboard.addListener('keyboardWillHide', this.keyboardWillHide.bind(this));
  }

  componentWillUnmount() {
    this.keyboardWillShowSub.remove();
    this.keyboardWillHideSub.remove();
  }
```

**Comment by gsavvid** [comment]
Keep in mind that `keyboardWillShow` and `keyboardWillHide` don't work for Android, whereas `keyboardDidShow` and `keyboardDidHide` **do** work. [Reference](https://github.com/facebook/react-native/issues/3468).

**Comment by BarakChamo** [comment]
Is there a plan or an idea of how to work towards an implementation of `keyboardWillShow` and `keyboardWillHide` on Android?

**Comment by Andr3wHur5t** [comment]
You should avoid using this module for android. 

Android has native functionality that handles this which will deal with fragmentation of behavior better than this module.

Ref https://github.com/Andr3wHur5t/react-native-keyboard-spacer/issues/46

If you are still seeing this behavior on iOS could file another issue?

**Comment by revi4n4** [comment]
async componentWillMount () {
          Keyboard.addListener('keyboardDidShow', (e) => this.keyboardWillShow(e));
         Keyboard.addListener('keyboardDidHide', (e) => this.keyboardWillHide(e));
}

keyboardWillShow = (event) => {
    console.log('Keyboard is show');
}
keyboardWillHide = (event) => {
 console.log('Keyboard hide');
}


work on ios & android
