### ISSUE TITLE
Support in Auto-Suggest

### ISSUE THREAD

**Issue by geldarhb** [Andr3wHur5t/react-native-keyboard-spacer#27]
Hey,

I'm trying to use this awesome lib, but I'm having some difficulties when the auto-suggest panel is there. 
Is there any support for that?

Thanks,
Guy

**Comment by klaasman** [comment]
Hi @geldarhb, did you found a fix for this or am I missing something in the docs?

**Comment by vladkosinov** [comment]
@klaasman did you found a solution?

**Comment by klaasman** [comment]
Sorry, but I’m afraid it has been too long ago for me to remember a solution..
