### ISSUE TITLE
Keyboard  is not found

### ISSUE THREAD

**Issue by Rice-M** [Andr3wHur5t/react-native-keyboard-spacer#28]
Keyboard  is not found  did you  mean DeviceEventEmitter?

**Comment by Andr3wHur5t** [comment]
What version of react-native are you using?

if its pre v27.X you will need to downgrade to v0.2.X of this module.

**Comment by Rice-M** [comment]
oh,thanks, I am still using v26.x.

**Comment by geirman** [comment]
I was confused by this too. However, looking at the v0.28 docs, I don't see any mention of Keyboard. Maybe that's one reason they put a freeze on core so they could bring docs up to speed.

**Comment by ma5069073** [comment]
I am using v29.x,but can not find Keyboard?

**Comment by sibelius** [comment]
@Andr3wHur5t we can close this
