### ISSUE TITLE
Yellow warning keyboard will show event should be registered via keyboard module

### ISSUE THREAD

**Issue by arstiefel** [Andr3wHur5t/react-native-keyboard-spacer#34]
When using the spacer I get a yellow warning with the following

![simulator screen shot jun 29 2016 2 17 16 pm](https://cloud.githubusercontent.com/assets/5383963/16463563/53d22cce-3e04-11e6-97b4-0eaaed241087.png)
#23 does not seem to have been resolved

**Comment by arstiefel** [comment]
Closing issue. Wasn't pulling correct version.

**Comment by zbbzbl0523** [comment]
i got this warning right now, which version will be correct?
"react": "^15.4.0",
"react-native": "^0.38.0",
