### ISSUE TITLE
pushes everything down instead of up

### ISSUE THREAD

**Issue by esthor** [Andr3wHur5t/react-native-keyboard-spacer#36]
When the keyboard is brought up, the animation moves everything down instead of up! The opposite of what is desired...

**Comment by Andr3wHur5t** [comment]
Can you ensure you view hierarchy looks like this?

```
<view>
  /*Your views here*/
  <keyboardSpacer>
</view>
```

**Comment by esthor** [comment]
I have a ScrollView around everything, so it's like this:

```
<ScrollView)
/*all views and such*/
<KeyboardSpacer/>
</ScrollView>
```

EDIT: And now that I placed the KeyboardSpacer back in there, no animation is happening 😕

**Comment by Andr3wHur5t** [comment]
You will need to put the keyboard spacer below and outside of the the scroll view to make the scroll view shrink and not overlap with the keyboard.

```
<View>
    <ScrollView>
        /*Other Views*/
    </ScrollView>
    <KeyboardSpacer/>
</View>
``q
```

**Comment by esthor** [comment]
Thanks!
