### ISSUE TITLE
deprecated this package ?

### ISSUE THREAD

**Issue by sibelius** [Andr3wHur5t/react-native-keyboard-spacer#38]
as KeyboardAvoidingView is open sourced on RN core - https://github.com/facebook/react-native/commit/8b78846a9501ef9c5ce9d1e18ee104bfae76af2e

should we deprecated this package?

**Comment by Andr3wHur5t** [comment]
I've been watching that commit, I can see it either way.

What to people using this module think; deprecate (👍) or don't (👎 )?

**Comment by rturk** [comment]
I wasn't able to use KeyboardAvoidingView to solve my issue
https://github.com/Andr3wHur5t/react-native-keyboard-spacer/issues/37. Maybe my code (View structure) needs extra work, I'll test KeyboardAvoidingView again in the next RN release.

**Comment by rclai** [comment]
I tried to use the `KeyboardAvoidingView` to do a chat text input fixed to the bottom, but it did not work out of the box, so I'm sticking to this. Please don't deprecate, at least not yet. I'm using RN `0.30.0`.

**Comment by jlyman** [comment]
In a couple of different instances I've still seen this package performing better than `KeyboardAvoidingView`, so I'd love to see it maintained just until the native component reaches parity. 😄

**Comment by dhaspden** [comment]
I'm using a mix of this and `KeyboardAvoidingView`.  I think this package still fits some cases where `KeyboardAvoidingView` doesn't.  In particular I have a chat window where the chat input hugs the bottom of the screen.  I have a much easier time pushing it up with that package than I do with `KeyboardAvoidingView`.

**Comment by JAStanton** [comment]
I found that there are some version of Android w/ keyboard that overlay, and some with keyboard that push / resize the remaining window. The ones that overlay, `react-native-keyboard-spacer` works great, the ones that push or resize the window `react-native-keyboard-spacer` isn't needed, but since it's been used, will add a keyboard sized margin in on top of the keyboard which looks really bad. I tested all keyboard on the `KeyboardAvoidingView` and it works great. 

That's my $0.02.

**Comment by pennersr** [comment]
Unfortunately, `KeyboardAvoidingView` has no support for hooking up custom code when the keyboard appears, as can be done with the `onToggle` of `react-native-keyboard-spacer`

**Comment by lacymorrow** [comment]
not yet

**Comment by PaulAndreRada** [comment]
KeyboardAvoidingView has rarely functioned the way it's supposed to for me. I'm very glad this package is not deprecated.

**Comment by alexcurtis** [comment]
I totally agree with the above. Please do not deprecate. This package works far better than KeyboardAvoidingView!

**Comment by sibelius** [comment]
this package is working better than `KeyboardAvoidingView`, it should be used on iOS only

**Comment by fritx** [comment]
react-native-keyboard-spacer is awesome! :+1:

Btw, my module [react-native-auto-scroll](https://github.com/fritx/react-native-auto-scroll) is working well with it, both on Android and iOS.

**Comment by zire** [comment]
This is much better than the native KeyboardAvoidView. Please do not deprecate.
