### ISSUE TITLE
navigator hiding in android when keyboard open

### ISSUE THREAD

**Issue by prashanthmerugucs** [Andr3wHur5t/react-native-keyboard-spacer#45]
**In ios working fine**

![ios-keyboard-dismiss](https://cloud.githubusercontent.com/assets/14312487/21642587/4b7aaf8a-d2a9-11e6-9b1c-aec7c22a2096.png)
![ios-keyboard-open](https://cloud.githubusercontent.com/assets/14312487/21642585/4b785082-d2a9-11e6-957e-191a43257a21.png)

**In android  i ahve a problem (like hiding navigator)**

![android-keyboard-dismiss-mode](https://cloud.githubusercontent.com/assets/14312487/21642598/67756df6-d2a9-11e6-8b10-781fea719191.png)
![android-keyboard-open](https://cloud.githubusercontent.com/assets/14312487/21642599/67b16fc2-d2a9-11e6-9945-63fa77c1d7fa.png)

**Comment by Fxxx327** [comment]
I have also encountered the same problem :(
![wx20170116-164919](https://cloud.githubusercontent.com/assets/13151619/21976231/d58040da-dc0b-11e6-8740-786e3c1d019f.png)
![wx20170116-164942](https://cloud.githubusercontent.com/assets/13151619/21976236/d9fd9612-dc0b-11e6-985c-52184423405b.png)

**Comment by prashanthmerugucs** [comment]
I found a solution for android 
open up ./android/app/src/main/AndroidManifest.xml and add android:windowSoftInputMode="adjustResize" within the .MainActivity activity declaration. It should look something like: 
<activity
  android:name=".MainActivity"
  android:label="@string/app_name"
  **android:windowSoftInputMode="adjustResize"**
  android:configChanges="keyboard|keyboardHidden|orientation|screenSize">
  <intent-filter>
      <action android:name="android.intent.action.MAIN" />
      <category android:name="android.intent.category.LAUNCHER" />
  </intent-filter>
</activity>

**Comment by Andr3wHur5t** [comment]
Closing as this seems resolved;

**Comment by ChawkiOS** [comment]
> Closing as this seems resolved;

It's not resolved yet !
