### ISSUE TITLE
Close keyboard by swipe down

### ISSUE THREAD

**Issue by jvlobo** [Andr3wHur5t/react-native-keyboard-spacer#6]
Hey there, great component you guys have built! thanks.

I was wondering if it'd be possible to close the keyboard when you swipe from top to bottom, as Whatsapp does.

Thanks.

**Comment by Andr3wHur5t** [comment]
Sorry for the latency,

This component just watches the keyboard position and size but you should be able to accomplish this effect using a iOS scroll view with `keyboardDismissMode` set to `DismissModeInteractive`.

https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIScrollView_Class/#//apple_ref/c/tdef/UIScrollViewKeyboardDismissMode

I'm unsure if this is implemented in react native ATM but I'm sure they would accept a PR.
