### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by sbycrosz** [Andr3wHur5t/react-native-keyboard-spacer#7]
The component doesn't resize itself when keyboard is shown :cry: 

Edit: seems to be an issue with RN https://github.com/facebook/react-native/issues/3468

**Comment by Andr3wHur5t** [comment]
Looking into this.

**Comment by sbycrosz** [comment]
So, I tried using `keyboardDidShow` and `keyboardDidHide` event instead, and it looks pretty good.

![keyboardanimation](https://cloud.githubusercontent.com/assets/4867178/13285159/2440cffc-db34-11e5-8520-3338674acc7f.gif)

p.s. unrelated but those android vanilla bounce effect looks really nice on a device. Maybe we could expose them as props?

**Comment by geirman** [comment]
You should probably update the Readme.md. I initially didn't even consider this package because I didn't think it supported Android based on the statement, "Plug and play iOS react-native keyboard spacer view." found in the readme.
