### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by dextermb** [Andr3wHur5t/react-native-keyboard-spacer#75]
@Andr3wHur5t, this library hasn't been updated for 11 months and there seems to be issues which haven't been resolved.

Is this package still maintained? I assume not

**Comment by pgerochi** [comment]
@Andr3wHur5t is there anyway we can look into the pull request and merge them? there are a few things that i need that people have fixed.

**Comment by heyman333** [comment]
yeah I think the author have to find other maintainer for React-Native env

**Comment by dextermb** [comment]
Library is not maintained. Would recommend using another keyboard spacer that is actively being developed on.
